config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#top'
  get 'home/about', to: 'home#about'
  get 'recruitments', to: 'recruitments#index'

  resources :users, only: [:show, :edit, :update, :hide, :destroy, :index] do
    member do
      get 'hide'
      put 'approval'
      put 'not_approval'
      delete 'destroy_personal_data'
    end
  end
  resources :profiles, only: [:new, :create, :edit, :update, :index, :show]
  resources :companies, only: [:new, :create, :index, :show, :edit, :update] do
    resources :works, only: [:new, :create, :index, :show, :edit, :update] do
       member do
         put 'hide'
         put 'reopen'
       end
    end
    member do
      put 'hide'
      put 'reopen'
      get 'information'
      patch 'info_up'
      get 'member_list'
    end
  end
  resource :company_members, only: [:create, :destroy]
  resources :communicates, only: [:new, :create, :index, :show]
  resources :talk_rooms, only: [:new, :create, :index, :show, :destroy] do
    resource :talks, only: [:new, :create, :destroy]
  end
end

app/models/work.rb
class Work < ApplicationRecord
	belongs_to :company

	validates :introduction, presence: true, length: {maximum: 500}
	validates :job_details, presence: true, length: {maximum: 2000}

	attachment :image, destroy: false	
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
	
	def new
		if user_signed_in?
			@work = Work.new
			@company = Company.find(params[:company_id])
			if current_user.belongs_to?(@company) == false
				redirect_to user_path(current_user)
			end
		else
			redirect_to root_path
		end
	end

	def create
		@work = Work.new(work_params)
		@work.user_id = current_user.id
		@company = Company.find(params[:company_id])
		@work.company_id = @company.id
    	if  @work.save
        	redirect_to company_work_path(@company, @work.id), notice: "新規登録が完了しました"
    	else
		@company = Company.find(params[:company_id])
        render 'new'
    	end
	end

	def index
		@company = Company.find(params[:company_id])
		if user_signed_in?
			if current_user.belongs_to?(@company)
			  @works = @company.works
			else
			  @works = @company.works.where(is_active: true)
			end
		else
			@works = @company.works.where(is_active: true)
		end
	end

	def hide
		@work = Work.find(params[:id])
		@work.user_id = current_user.id
		@company = Company.find(params[:company_id])
		@work.company_id = @company.id
		@work.update(is_active: false)
		redirect_to company_works_path, notice: "#{@work.title}の掲載を停止しました"
	end

	def reopen

		@work = Work.find(params[:id])
		@work.user_id = current_user.id
		@company = Company.find(params[:company_id])
		@work.company_id = @company.id
		@work.update(is_active: true)
		redirect_to company_works_path, notice: "#{@work.title}の掲載を再開しました"
	end

	def show
		@work = Work.find(params[:id])
		@company = Company.find(params[:company_id])
		@users = @company.users.limit 12
		if user_signed_in?
		  @work.user_id = current_user.id
		  if CompanyMember.find_by(user_id: current_user.id).present?
		      belongsCompany = CompanyMember.find_by(user_id: current_user.id)
		      @belongs_company = Company.find(belongsCompany.company_id)
	  	  end
		  @talk_room = TalkRoom.find_by(company_id: @work.company, user_id: current_user.id)
		end
	end

	def edit
		if user_signed_in?
			@work = Work.find(params[:id])
			@work.user_id = current_user.id
			@company = Company.find(params[:company_id])
			if current_user.belongs_to?(@company) == false
				redirect_to user_path(current_user)
			end
		else
			redirect_to root_path
		end
	end

	def update
		@work = Work.find(params[:id])
		@work.user_id = current_user.id
		@company = Company.find(params[:company_id])
		@work.company_id = @company.id
		@work.update(work_params)
		redirect_to company_work_path, notice: "#{@company.name}の求人内容を更新しました"
	end

	private
  	def work_params
   		params.require(:work).permit(:company_id, :user_id, :title, :introduction, :job_details, :image, :is_active)
	end

end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/edit.html.erb
<%= render "layouts/error", obj: @work %>


<h2>募集内容編集</h2>

<%= form_with model: [@company, @work] do |f| %>
	<br>
	<h3>タイトル</h3>
	<p>（検索結果トップに表示されます）</p>
	<div><%= f.text_area :title, class: "form-text-title form-control" , rows: 1 %></div>
		 <div class="field">

	<br>
	<h3>紹介文</h3>
	<p>（検索結果トップに表示されます）</p>
		<div><%= f.text_area :introduction, class: "form-text-area form-control js-text3" ,id: "input-text", rows: 6 %></div>
		<P class="js-text3-count pull-right"></P>
	<br>
	<h3>募集要項 詳細</h3>
		<div><%= f.text_area :job_details, class: "form-text-area form-control js-text4" , rows: 15 %></div>
		<P class="js-text4-count pull-right"></P>
	<br>
	<div class="field">
	  	<%= f.label "画像" %><br />
	    <%= attachment_image_tag @work, :image, :fill, 250, 250, fallback: "no_image_white.png", size:'60x60' %>
	  	<%= f.attachment_field :image %>
	</div>

	<br>
	<div class="btn-center"><%= f.submit "変更する", class:"btn btn-warning" %></div>
<% end %>
<br><br>

app/views/works/index.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: key) %>
<% end %>

<div class="row col-sm-12">
	<% if @works.blank? %>
		<p>現在募集はしていません</p>
	<% else %>
		<% @works.each do |work| %>
			<%= link_to company_work_path(work.company.id, work.id) do %>
				<div class="line"></div>
				<div><%= attachment_image_tag work, :image, :fill,  978, 300, fallback: "no_image_gray.png", size:'978x280' %></div>
				<h3><%= work.title %></h3>
				<p><%= simple_format(work.introduction) %></p>
			<% end %>
			<table class="table-hover">
				<tr>
					<td class="col-sm-3"><%= link_to company_path(work.company.id) do %>
							<%= attachment_image_tag work.company, :image, :fill, 60, 60, fallback: "no_image_white.png", size:'60x60', class:"img-circle" %>
						<% end %>
					</td>
				    <td class="col-sm-5"><%= link_to company_path(work.company.id) do %>
					    	<%= work.company.name %>
				    	<% end %><br>
				    	<%= work.company.address_prefecture %>
				    </td><br>

					<% if user_signed_in? %>
						<% if current_user.belongs_to?(work.company) %>
							<div class="work-btn-flex">
								<div class="work-btn-margin"><td class="col-sm-2"><%= link_to "募集内容を編集する", edit_company_work_path(work.company.id, work.id), class: "btn btn-warning  btn-sm", data: {"turbolinks" => false} %></td>
								</div><br>

								<% if work.is_active == 1 %>
									<td class="col-sm-2"><%= form_with(model:[work.company,work],url: hide_company_work_path(work.company.id, work.id), method: :put) do |f| %>
											<%= f.submit "掲載を停止する", class: "btn btn-warning  btn-sm work-btn-margin" %>	
									<% end %></td>
									
								<% else %>
									<td><%= form_with(model:[work.company,work],url: reopen_company_work_path(work.company.id, work.id), method: :put) do |f| %>
											<%= f.submit "募集を再開する", class: "btn btn-default  btn-sm work-btn-margin" %>	
									<% end %></td>
								<% end %>
							</div>
						<% end %>
					<% end %>
				</tr>
			</table>	
		<% end %>
	<% end %>
<br><br>
</div>
<br><br>

app/views/works/new.html.erb
<%= render "layouts/error", obj: @work %>

<h2>募集内容登録</h2>

<%= form_with model: [@company, @work] ,data: {remote: false} do |f| %>
	<br>
	<h3>タイトル</h3>
	<p>（検索結果トップに表示されます）</p>
	<div><%= f.text_area :title, class: "form-text-title form-control" , rows: 1 %></div>
		 <div class="field">

	<br>
	<h3>紹介文</h3>
	<p>（検索結果トップに表示されます）</p>
		<div><%= f.text_area :introduction, class: "form-text-area form-control js-text5", rows: 6 %></div>
		<P class="js-text5-count pull-right"></P>

	<br>
	<h3>募集要項 詳細</h3>
		<div><%= f.text_area :job_details, class: "form-text-area form-control js-text6", rows: 15 %></div>
		<P class="js-text6-count pull-right"></P>

	<br>
	<div class="field">
	  	<%= f.label "画像" %><br />
	    <%= attachment_image_tag @work, :image, :fill, 250, 250, fallback: "no_image_white.png", size:'60x60' %>
	  	<%= f.attachment_field :image %>
	</div>

	<br>	
	<div><%= f.submit "登録する", class:"btn btn-warning" %></div>
<% end %>
<br><br>

app/views/works/show.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: key) %>
<% end %>

<h2><strong><%= @work.title %></strong></h2>
<div>
	<table>
		<tr>
			<td><%= link_to company_path(@work.company.id) do %>
					<%= attachment_image_tag @work.company, :image, :fill, 100, 100, fallback: "no_image_white.png", size:'50x50', class:"img-circle" %>
				<% end %>
			</td>
		    <td><%= link_to company_path(@work.company.id) do %>
			    	<%= @work.company.name %>
		    	<% end %>
		    </td>
	</table>
</div>

<br>
<div><%= attachment_image_tag @work, :image, :fill, 978, 398 %></div>


<br>
<div>
	<h3><strong><%= "#{@work.company.name}のメンバー" %></strong></h3>
	<% if @users.blank? == false %>
		<div class="right-link">
			<%= link_to "ほかのメンバーもみる ＞＞", member_list_company_path(@company) %>
		</div>
		<div class="company-member-flex row col-sm-12">		
			<% @users.each do |user| %>
				<div class="col-sm-2">
					<% if Profile.where(user_id: user).blank? %>
						<%= attachment_image_tag user, :image, :fill, 100, 100, fallback: "no_image_human.jpeg", size:'100x100', class:"img-circle" %> <br />
						<p><%= user.nic_name %></p>
					<% else %>
						<%= link_to profile_path(user.profile) do %>
							<%= attachment_image_tag user, :image, :fill, 100, 100, fallback: "no_image_human.jpeg", size:'100x100', class:"img-circle" %> <br />
							<p><%= user.nic_name %></p>
							<%= hidden_field_tag :id, :value => user.profile.id %>
						<% end %>
					<% end %>
				</div>
			<% end %>
		</div>
	<% else %>
	<p>現在メンバー登録はありません</p>
	<% end %>
</div>

<br>
<div class="row col-sm-12">
	<h3><strong>事業内容</strong></h3>

	<% if user_signed_in? %>
		<% if current_user.belongs_to?(@company) %>
			<div class="secret-btn-right"><%= link_to "会社の紹介文を編集する", information_company_path(@company.id), class: "btn btn-warning  btn-sm", data: {"turbolinks" => false} %></div>
			<br>
		<% end %>
	<% end %>

	<div class="company-flex">
		<div class="image_left"><%= attachment_image_tag @work.company, :i_image1, :fill, 469, 250, class: "img-rounded" %></div>
		<div><%= attachment_image_tag @work.company, :i_image2, :fill, 469, 250, class: "img-rounded" %></div>
	</div>

	<p><%= simple_format(@work.company.introduction) %></p>
</div>

<br>
<div class="row col-sm-12">
	<h3><strong>今後の展望</strong></h3>

	<div class="company-flex">
		<div class="image_left"><%= attachment_image_tag @work.company, :f_image1, :fill, 469, 250, class: "img-rounded" %></div>
		<div><%= attachment_image_tag @work.company, :f_image2, :fill, 469, 250, class: "img-rounded" %></div>
	</div>

	<p><%= simple_format(@work.company.future) %></p>
</div>

<br>
<div class="row col-sm-12">
	<h3><strong>募集内容</strong></h3>

	
		<% if user_signed_in? %>
			<% if current_user.belongs_to?(@company) %>
				<div class="work-btn-flex">
					<div class="work-btn-margin"><%= link_to "募集内容を編集する", edit_company_work_path(@company.id, @work.id), class: "btn btn-warning  btn-sm", data: {"turbolinks" => false} %>
					</div><br>

					<% if @work.is_active == 1 %>
						<div class="work-btn-margin">
							<%= form_with model: @work, url: hide_company_work_path(@company, @work), method: :put do |f| %>

									<%= f.hidden_field :is_active, value: false  %>
									<%= f.submit "募集を停止する", class: "btn btn-warning btn-sm" %>	
							<% end %>
						</div>
					<% else %>
						<div class="work-btn-margin">
							<%= form_with model: @work, url: reopen_company_work_path(@company, @work), method: :put do |f| %>

									<%= f.hidden_field :is_active, value: true  %>
									<%= f.submit "募集を再開する", class: "btn btn-warning btn-sm" %>
							<% end %>
						</div>
					<% end %>
				</div>
			<% end %>
		<% end %>
	<br>
	<div><%= simple_format(@work.job_details) %></div>
</div>

<br>
<div class="row col-sm-12">
	<% if user_signed_in? %>
		<% if current_user.belongs_to?(@belongs_company) %>
		　　<p></p>	
		<% else %>			
			<% if TalkRoom.find_by(company_id: @work.company, user_id: current_user.id).present? %>
				<div class="btn-center">
					<%= link_to "メッセージを送る", talk_room_path(@talk_room), class: "btn btn-danger btn-lg" %>
				</div>
			<% else %>
				<div class="btn-center">
					<%= form_with(url: talk_rooms_path, method: :post) do |f| %>
						<%= f.hidden_field :company_id, :value => @company.id %>
						<%= f.hidden_field :user_id, :value => current_user.id %>
						<%= f.submit "メッセージを送る", class: "btn btn-success btn-lg" %>
					<% end %>
				</div>
			<% end %>
		<% end %>
	<% else %>
		<%= link_to "ログインしてシゴトの詳細を聞く", user_session_path , class: "btn btn-success  btn-sm" %>
	<% end %>
	<br>
<br>
</div>
<br>
<br>