config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#top'
  get 'home/about', to: 'home#about'
  get 'recruitments', to: 'recruitments#index'

  resources :users, only: [:show, :edit, :update, :hide, :destroy, :index] do
    member do
      get 'hide'
      put 'approval'
      put 'not_approval'
      delete 'destroy_personal_data'
    end
  end
  resources :profiles, only: [:new, :create, :edit, :update, :index, :show]
  resources :companies, only: [:new, :create, :index, :show, :edit, :update] do
    resources :works, only: [:new, :create, :index, :show, :edit, :update] do
       member do
         put 'hide'
         put 'reopen'
       end
    end
    member do
      put 'hide'
      put 'reopen'
      get 'information'
      patch 'info_up'
      get 'member_list'
    end
  end
  resource :company_members, only: [:create, :destroy]
  resources :communicates, only: [:new, :create, :index, :show]
  resources :talk_rooms, only: [:new, :create, :index, :show, :destroy] do
    resource :talks, only: [:new, :create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :profile, dependent: :delete

  has_many :company_members, dependent: :destroy
  has_many :companies, through: :company_members
  accepts_nested_attributes_for :company_members

  has_many :works, dependent: :destroy
  has_many :work_companies, through: :works
  accepts_nested_attributes_for :works

  has_many :talk_rooms, dependent: :destroy
  has_many :talk_room_companies, through: :talk_rooms
  accepts_nested_attributes_for :talk_rooms

  has_many :talks, dependent: :destroy
  has_many :talk_rooms, through: :talks
  accepts_nested_attributes_for :talks

  # メッセージ送信側
  # 送信者のUserから見て、宛先（受信者）のUserを(中間テーブルを介して)集める。ユーザーの判別は 'sent_msgs(送信者)'カラムで行う。
  has_many :communicates, foreign_key: 'user_id', dependent: :destroy
  # 中間テーブル(messages)を介して「destination」モデルのUser(宛名)「destination_id」を集めることを「sent(送信済みメッセージ)」と定義
  has_many :sent_msgs, through: :communicates, source: :destination

  # メッセージ受信側
  # 受信者から見て、送信者のUserを(中間テーブルを介して)集める。ユーザーの判別は ’destination_id(宛先)’カラムで行う。
  has_many :receive_communicates, class_name: 'Communicate', foreign_key: 'destination_id', dependent: :destroy
  # 中間テーブル(messages)を介して「user」モデルのUser(送信者)「user_id」を集めることを「received_msgs」と定義
  has_many :received_msgs, through: :receive_communicates, source: :user


  validates :name, presence: true, length: {minimum: 2, maximum: 30}
  validates :name_kana, presence: true, length: {minimum: 2, maximum: 30}, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :nic_name, presence: true, length: {minimum: 2, maximum: 10}
  validates :birthday, length: {is: 8}
  validates :email, presence: true, length: {minimum: 5, maximum: 50}
  validates :zip_code, length: {is: 7}, format: { with: /\A[0-9]+\z/, message: 'はハイフンなし、半角数字で入力して下さい。'}
  validates :address_prefecture_name, length: {minimum: 1, maximum: 5}
  validates :address_city, length: {maximum: 15}
  validates :address_line1, length: {maximum: 20}
  validates :address_line2, length: {maximum: 20}
  validates :phone_number, length: {minimum: 3, maximum: 15}, format: { with: /\A[0-9]+\z/, message: 'はハイフンなし、半角数字で入力して下さい。'}

  enum sex: {男性: 0, 女性: 1}
  enum permissions: {nomal: 0, company_rep: 1, admin: 2}

  attachment :image, destroy: false


  def belongs_to?(company)
    self.company_rep? && company.users.include?(self)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def show
		@user = current_user
        @companies = @user.companies
        @zip_code =  "〒" + @user.zip_code[0..2] + "-" + @user.zip_code[3..6]
        @address = @user.address_prefecture_name + @user.address_city + @user.address_line1 + @user.address_line2
        @phone_number = @user.phone_number[0..2] + "-" + @user.phone_number[3..6] + "-" + @user.phone_number[7..10]
	end

	def edit
		@user = current_user
	end

	def update
		@user = current_user
		if @user.update(user_params)
      		redirect_to user_path(current_user.id), notice: "基本登録情報を変更しました"
        else
      		@user = current_user   
      		render "edit"
    	end
	end

	def hide
		@user = current_user
    end

    def destroy_personal_data
    	@user = current_user
    	@user.destroy
    	redirect_to root_path,  notice: "登録情報を削除しました。またのご利用をお待ちしております。"
    end

    def index
    	if current_user.permissions != "admin"
    		@user = current_user
 	  	 	redirect_to user_path(current_user.id)
 	  	else
 	  		@admin = current_user
 	  	 	@users = User.all
 	  	end
    end

    def not_approval
    	@user = User.find(params[:id])
    	if @user.update(permissions: 0)
    		redirect_to users_path
    	else
	    	@admin = current_user
	    	@users = User.all
	    	render 'index'
    	end
    end

    def approval
    	@user = User.find(params[:id])
    	if @user.update(permissions: 1)
    		redirect_to users_path
    	else
	    	@admin = current_user
	    	@users = User.all
	    	render 'index'
    	end
    end
    

    private
  	def user_params
   		params.require(:user).permit(:email, :name, :name_kana, :nic_name, :birthday, :zip_code, :address_prefecture_name, :address_city, :address_line1, :address_line2, :phone_number, {permissions: params[:permissions]}, :image, :sex)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render "layouts/error", obj: @user %>

<h2>ユーザー基本情報編集</h2>

<%= form_for(@user, url: user_path) do |f| %>
	<table class="table row col-sm-12">
		<tr>
			<th></th>
			<td><%= attachment_image_tag @user, :image, :fill, 150, 150, fallback: "no_image_human.jpg" %><br>
			    <%= f.attachment_field :image %></td>
		</tr>
		<tr>
			<th class="col-sm-3">名前</th>
			<td><%= f.text_field :name %></td>
		</tr>
		<tr>
			<th>フリガナ（全角カタカナ）</th>
			<td><%= f.text_field :name_kana %></td>
		</tr>
		<tr>
			<th>表示名</th>
			<td><%= f.text_field :nic_name %></td>
		</tr>
		<tr>
			<th>性別</th>
			<td>
				<%= f.radio_button :sex, :男性, { selected: @user.sex_before_type_cast } %>
    			<%= f.label :男性 %>
				<%= f.radio_button :sex, :女性, { selected: @user.sex_before_type_cast } %>
    			<%= f.label :女性 %>

  			</td>
		</tr>
		<tr>
			<th>誕生日</th>
			<td><%= f.text_field :birthday %></td>
		</tr>
		<tr>
			<th>メール</th>
			<td><%= f.email_field :email %></td>
		</tr>
		<tr>
			<th>郵便番号（ハイフンなし）</th>
			<td><%= f.text_field :zip_code %></td>
		</tr>
		<tr>
			<th>住所（都道府県）</th>
			<td><%= f.text_field :address_prefecture_name %></td>
		</tr>
		<tr>
			<th>住所（市区郡町村）</th>
			<td><%= f.text_field :address_city %></td>
		</tr>
		<tr>
			<th>住所（町名・番地）</th>
			<td><%= f.text_field :address_line1 %></td>
		</tr>
		<tr>
			<th>住所（建物名・号室）</th>
			<td><%= f.text_field :address_line2 %></td>
		</tr>
		<tr>
			<th>電話（ハイフンなし）</th>
			<td><%= f.text_field :phone_number %></td>
		</tr>
		<tr>
			<th class="col-sm-3"></th>
			<td class="col-sm-2"></td>
			<td><%= f.submit "編集内容を保存する",class:"btn btn-success" %></td>
		</tr>
	</table>
<br><br>
<% end %>

app/views/users/hide.html.erb
<br><br><br>

<div>
	<div class="text-hide-message">
		<p>退会すると、</p>
		<p>企業とのトーク履歴</p>
		<p>作成されたPRページの情報　が</p>
		<p>削除されてしまいます。</p>
		<p>本当に退会しますか？</p>
	</div>
<br><br>	
	<div class="profile-btn-flex">
		<div class="profile-btns">
			<%= link_to user_path(current_user) do %>
				<button class="btn btn-warning">退会しない</button>
			<% end %>
		</div>
		<div class="profile-btns">
			<%= link_to  destroy_personal_data_user_path(current_user), method: :delete do %>
				<button class="btn btn-success">退会する</button>
			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<h2>ユーザー一覧</h2>
<table class="table">
	<thead>
		<tr>
			<th>名前</th>
			<th>フリガナ</th>
			<th>表示名</th>
			<th>性別</th>
			<th>生年月日</th>
			<th></th>
			<th>電話</th>
			<th>メール</th>
			<th>権限タイプ</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>
			<tr>
				<td><%= user.name %></td>
				<td><%= user.name_kana %></td>
				<td><%= user.nic_name %></td>
				<td><%= user.sex %></td>
				<td>
					<% birthday = user.birthday %>
					<% birthday_date = birthday.to_date %>
					<%= birthday_date.strftime("%Y/%m/%d") %>
				</td>
				<td>
					<% birthday2 = birthday.to_i %>
					<% day = Date.today %>
					<% day.to_date %>
					<% day2 = day.strftime("%Y%m%d").to_i %>
					<%= age = (day2 - birthday2) / 10000 %>
				</td>
				<td><%= user.phone_number[0..2] + "-" + user.phone_number[3..6] + "-" + user.phone_number[0..2] %></td>
				<td><%= user.email %></td>
				<td><% if user.permissions != "admin" %>
						<% if user.permissions == "company_rep" %>
							<%= form_with(model:user ,url: not_approval_user_path(user.id), method: :put) do |f| %>
									<%= f.submit "企業担当者", class: "btn btn-warning  btn-sm" %>
							<% end %>
						<% else %>
							<%= form_with(model:user ,url: approval_user_path(user.id), method: :put) do |f| %>
									<%= f.submit "一般", class: "btn btn-default  btn-sm" %>
							<% end %>
						<% end %>
					<% else %>
						<span>管理者</span>
					<% end %>
				</td>		
			</tr>
		<% end %>
	</tbody>
</table>

<div class="btn-center">
	<%= link_to user_path(current_user.id) do %>
	<button class="btn btn-primary">マイページに戻る</button>
	<% end %>
</div>

app/views/users/show.html.erb
<!-- エラー、サクセスメッセージ -->
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: key) %>
<% end %>

<!-- エラー、サクセスメッセージ -->

<h3>基本登録情報</h3>	


<% if current_user.admin? %>
	<div class="all-users-flex btns">
		<div>
			<%= link_to users_path do %>
				<button class="standerd_btn_dark-blue users_btn">
					ユーザー一覧へ
				</button>
			<% end %>
		</div>
		<div>
			<%= link_to new_company_path do %>
				<button class="standerd_btn_dark-blue users_btn">
					会社情報を登録をする
				</button>
			<% end %>
		</div>
	</div>
<% end %>


<!-- ログイン済み全ユーザー表示 -->
<div class="all-users-flex btns">
	<% if TalkRoom.where(user_id: current_user.id).any? %>
		<div>
			<%= link_to talk_rooms_path do |f| %>
				<button class="standerd_btn_blue users_btn">トークルームを確認する</button>
			<% end %>
		</div>
	<% end %>
	<div>
		<%= link_to edit_user_path(current_user.id) do %>
			<button class="standerd_btn_blue users_btn">基本登録情報を変更する</button>
		<% end %>
	</div>
	<div>
		<%= link_to edit_user_registration_path(current_user.id) do %>
			<button class="standerd_btn_blue users_btn">パスワードを変更する</button>
		<% end %>
	</div>
	<div>
		<% if current_user.profile.blank? %>
			<%= link_to new_profile_path, data: {"turbolinks" => false} do %>
				<button class="standerd_btn_blue users_btn">プロフィールを登録する</button>
			<% end %>
		<% else %>
			<%= link_to edit_profile_path(current_user.profile.id), data: {"turbolinks" => false} do %>
				<button class="standerd_btn_blue users_btn">プロフィールを編集する</button>
			<% end %>
		<% end %>
	</div>
</div>
<br>
<!-- ログイン済み全ユーザー表示 -->
<div>
	<% if current_user.company_members.exists? %>
		<% @companies.each do |company| %>
			<table class="table row col-sm-12">
				<tr>
					<th class="col-sm-2">所属企業</th>
					<td class="col-sm-2 belongs-companay-link">
						<%= link_to company_path(company.id) do %>
							<%= attachment_image_tag company, :image, :fill, 40, 40, fallback: "no_image_white.png", size:'40x40',  class:"img-circle" %>
						<% end %> <br>
						<%= link_to company_path(company.id) do %>
							<%= company.name %>
						<% end %>
					</td>
					<td class="col-sm-8"></td>
				</tr>
			</table>
		<% end %>
	<% end %>
</div>

<div class="row col-sm-12"><br><br>
	<div class="col-sm-3">
		<%= attachment_image_tag @user, :image, :fill, 200, 200, fallback: "no_image_human.jpg", size:'200x200',  class:"img-circle" %>
	</div>
	<div class="col-sm-9">
	<table class="table col-sm-9">
		<tr>
			<th class="col-sm-2">名前</th>
			<td class="col-sm-7"><%= @user.name %></td>
		</tr>
		<tr>
			<th class="col-sm-2">フリガナ</th>
			<td class="col-sm-7"><%= @user.name_kana %></td>
		</tr>
		<tr>
			<th class="col-sm-2">表示名</th>
			<td class="col-sm-7"><%= @user.nic_name %></td>
		</tr>
		<tr>
			<th class="col-sm-2">性別</th>
			<td class="col-sm-7"><%= @user.sex %></td>
		</tr>
		<tr>
			<th class="col-sm-2">誕生日</th>
			<td class="col-sm-7">
				<% birthday = @user.birthday.to_date %>
				<%= birthday.strftime("%Y/%m/%d") %></td>
		</tr>
		<tr>
			<th class="col-sm-2">メール</th>
			<td class="col-sm-7"><%= @user.email %></td>
		</tr>
		<tr>
			<th class="col-sm-2">住所</th>
			<td class="col-sm-7">
				<%= @zip_code %>  <br />
				<%= @address %>
			</td>
		</tr>
		<tr>
			<th class="col-sm-2">電話</th>
			<td class="col-sm-7"><%= @phone_number %></td>
		</tr>
		<tr>
			<th class="col-sm-2">パスワード</th>
			<td class="col-sm-7"><%= "*************" %></td>
		</tr>
		<tr>
			<th class="col-sm-2"></th>
			<td class="col-sm-5"></td>
			<td class="col-sm-2">
				<%= link_to hide_user_path class: "btn-center" do %>
					<button class="standerd_btn_red">退会する</button>
				<% end %>
			</td>
		</tr>
	</table>
	</div>
</div>

<br />


	<br><br>