config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#top'
  get 'home/about', to: 'home#about'
  get 'recruitments', to: 'recruitments#index'

  resources :users, only: [:show, :edit, :update, :hide, :destroy, :index] do
    member do
      get 'hide'
      put 'approval'
      put 'not_approval'
      delete 'destroy_personal_data'
    end
  end
  resources :profiles, only: [:new, :create, :edit, :update, :index, :show]
  resources :companies, only: [:new, :create, :index, :show, :edit, :update] do
    resources :works, only: [:new, :create, :index, :show, :edit, :update] do
       member do
         put 'hide'
         put 'reopen'
       end
    end
    member do
      put 'hide'
      put 'reopen'
      get 'information'
      patch 'info_up'
      get 'member_list'
    end
  end
  resource :company_members, only: [:create, :destroy]
  resources :communicates, only: [:new, :create, :index, :show]
  resources :talk_rooms, only: [:new, :create, :index, :show, :destroy] do
    resource :talks, only: [:new, :create, :destroy]
  end
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :company_members, dependent: :destroy
	has_many :users, through: :company_members
	accepts_nested_attributes_for :company_members

	has_many :works, dependent: :destroy
	has_many :work_users, through: :works
	accepts_nested_attributes_for :works

	has_many :talk_rooms, dependent: :destroy
	has_many :talk_room_users, through: :talk_rooms
	accepts_nested_attributes_for :talk_rooms

	validates :name, presence: true
	validates :name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
	validates :establishment, length: {is: 6}
	validates :email, presence: true, length: {minimum: 5, maximum: 50}
	validates :zip_code, length: {is: 7}, format: { with: /\A[0-9]+\z/, message: 'はハイフンなし、半角数字で入力して下さい。'}
	validates :address_prefecture, presence: true, length: {minimum: 1, maximum: 5}
	validates :address_city, length: {maximum: 15}
	validates :address_line1, length: {maximum: 30}
	validates :address_line2, length: {maximum: 50}
	validates :phone_number, presence: true, length: {minimum: 3, maximum: 15}, format: { with: /\A[0-9]+\z/, message: 'はハイフンなし、半角数字で入力して下さい。'}
    validates :introduction, length: {maximum: 1000}
    validates :future, length: {maximum: 1000}

	attachment :image, destroy: false
    attachment :i_image1, destroy: false
    attachment :i_image2, destroy: false
    attachment :f_image1, destroy: false
    attachment :f_image2, destroy: false
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController


	def new
		if user_signed_in?
			if current_user.admin?
				@company = Company.new
			else
				redirect_to user_path(current_user)
			end
		else
			redirect_to root_path
		end
	end

	def create
		@company = Company.new(company_params)
    	if  @company.save
        	redirect_to company_path(@company.id), notice: "新規登録が完了しました"
    	else
        	@user = current_user
        	render 'users/show'
    	end
	end

	def index
		@companies = Company.where(is_active: true)
		if user_signed_in?
			if current_user.admin?
				@companies = Company.all
			end
		else
		@companies = Company.where(is_active: true)
		end
	end

	def show
		@company = Company.find(params[:id])
		@users = @company.users.limit 12
		@user = current_user
		if user_signed_in?
		  @company_member = current_user.company_members.find_by(company_id: @company.id)
		end
	end

	def member_list
		@company = Company.find(params[:id])
		@users = @company.users
	end

	def hide
		@company = Company.find(params[:id])
		@company.update(company_params)
		redirect_to request.referer, notice: "#{@company.name}の利用を停止しました"
	end

	def reopen
		@company = Company.find(params[:id])
		@company.update(is_active: true)
		redirect_to request.referer, notice: "#{@company.name}の利用を再開しました"
	end

	def edit
		if user_signed_in?
			if current_user.admin?
				@company = Company.find(params[:id])
			end
		else
			redirect_to root_path
		end
	end

	def update
		@company = Company.find(params[:id])
		if @company.update(company_params)
      		redirect_to company_path(@company.id), notice: "#{@company.name}の会社情報を更新しました"
        else
      		@company = Company.find(params[:id])
      		render "edit"
    	end		
	end

	def information
		if user_signed_in?
			@company = Company.find(params[:id])
			if current_user.belongs_to?(@company) == false
				redirect_to user_path(current_user.id)
			end
		else
			redirect_to root_path
		end
	end

	def info_up
		@company = Company.find(params[:id])
		if @company.update(company_params)
      		redirect_to company_path(@company.id), notice: "#{@company.name}の会社情報を更新しました"
        else
      		@company = Company.find(params[:id])
      		render "edit"
    	end
	end

	private
  	def company_params
   		params.require(:company).permit(:name, :name_kana, :phone_number, :establishment, :url, :email, :zip_code, :address_prefecture, :address_city, :address_line1, :address_line2, :image, :is_active, :introduction, :future, :i_image1, :i_image2, :f_image1, :f_image2)
	end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/edit.html.erb
<%= render "layouts/error", obj: @company %>


<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: key) %>
<% end %>


<h3>会社基本情報編集</h3>

<%= form_with model: @company, method: :patch do |f| %>

  <div class="field">
    <%= f.label "会社名" %>
    <span class = "mandatory">&nbsp;<必須></span><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
    <span class = explanation>&nbsp; &nbsp;略称なし  入力例:'(株)'→'株式会社'と入力</span>
  </div>

  <div class="field">
    <%= f.label "フリガナ" %>
    <span class = "mandatory">&nbsp;<必須></span><br />
    <%= f.text_field :name_kana, autofocus: true, autocomplete: "name_kana" %>
    <span class = explanation>&nbsp; &nbsp;全角カタカナ</span>
  </div>

  <div class="field">
    <%= f.label "代表電話" %>
    <span  class = "mandatory">&nbsp;<必須></span><br />
    <%= f.text_field :phone_number, autofocus: true, autocomplete: "nic_name" %>
  </div>

  <div class="field">
    <%= f.label "創立年月" %><br />
    <%= f.text_field :establishment, autofocus: true %>
    <span class = "explanation" >&nbsp; &nbsp;' / 'なし<br>入力例:' 199006 '</span>
  </div>

  <div class="field">
    <%= f.label "url" %><br />
    <%= f.text_field :url, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label "メール" %>
    <span class = "mandatory">&nbsp;<必須></span><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label "郵便番号" %><br />
    <%= f.text_field :zip_code, autofocus: true, autocomplete: "zip_code" %>
    <span class = explanation>&nbsp; &nbsp;' - 'なし  入力例:' 1010001 '</span>
  </div>

  <div class="field">
    <%= f.label "住所（都道府県）" %>
    <span class = "mandatory">&nbsp;<必須></span><br />
    <%= f.text_field :address_prefecture, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label "住所（市区郡町村）" %><br />
    <%= f.text_field :address_city, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label "住所（町名 番地）" %><br />
    <%= f.text_field :address_line1, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label "住所（建物名 階層 号室）" %><br />
    <%= f.text_field :address_line2, autofocus: true %>
  </div>

  <div class="field">
  	<%= f.label "会社ロゴ画像" %><br />
	<%= attachment_image_tag @company, :image, :fill, 150, 150, fallback: "no_image_white.png", size:'150x150' %>
  	<%= f.attachment_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "変更する" %>
  </div>
<% end %>

app/views/companies/index.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: key) %>
<% end %>

<h2>カイシャ一覧</h2>
<div class="row col-sm-12">
	<table class="table table-hover">
		<% @companies.each do |company| %>
				<td class="col-sm-1">
					<%= link_to company_path(company.id) do %>
						<%= attachment_image_tag company, :image, :fill, 60, 60, fallback: "no_image_white.png", size:'60x60', class:"img-circle" %>
					<% end %>
				</td>
				<td class="col-sm-2"><%= link_to company_path(company.id) do %>
						<%= company.name %>
					<% end %>
					<br><%= company.url %>
					<br><div class="label label-danger"><%= company.address_prefecture %></div>
				</td>
				<td class="col-sm-6"><%= company.introduction %></td>
				<td class="col-sm-2"><%= link_to "この会社の詳細をみる", company_path(company), class: "btn btn-success  btn-sm" %>	
				</td>
				<% if user_signed_in? %>		
					<% if current_user.admin? %>
						<td>
							<div class="secret-btn-right">
								<%= link_to edit_company_path(company) do %>
									<button class="btn btn-primary btn-sm">基本情報を変更する</button>
								<% end %>
							</div>
						</td>
						<% if company.is_active == 1 %>
							<td class="col-sm-1">
								<div>
									<%= form_with model: company, url: hide_company_path(company), method: :put do |f| %>

											<%= f.hidden_field :is_active, value: false  %>
											<%= f.submit "停止する", class: "btn btn-primary  btn-sm" %>	
									<% end %>
								</div>
							</td>
						<% else %>
							<td class="col-sm-1">
								<div>
									<%= form_with model: company, url: reopen_company_path(company), method: :put do |f| %>

											<%= f.hidden_field :is_active, value: true  %>
											<%= f.submit "再開する", class: "btn btn-default  btn-sm" %>
									<% end %>
								</div>				
							</td>
						<% end %>	
					<% end %>
				<% end %>
			</tr>
		<% end %>
	</table>
</div>

app/views/companies/information.html.erb
<%= render "layouts/error", obj: @company %>

<h2>会社紹介登録</h2>

<%= form_with model: @company, url: info_up_company_path, method: :patch do |f| %>

	<br>
	<h3>会社紹介文</h3>
	<div class="form_wrapper">
		<div><%= f.text_area :introduction, class: "form-text-area form-control js-text1", rows: 6 %></div>
		<P class="js-text1-count pull-right"></P>
		<br>
		<div><%= f.label "画像①" %><br />
  			 <%= f.attachment_field :i_image1 %>
  			 <%= f.label "画像②" %><br />
  			 <%= f.attachment_field :i_image2 %></div>
  	</div>

  	<br>
	<h3>今後の展望</h3>
	<div class="form_wrapper">
		<div><%= f.text_area :future, class: "form-text-area form-control js-text2", rows: 6 %></div>
		<P class="js-text2-count pull-right"></P>
		<br>
		<div><%= f.label "画像①" %><br />
  			 <%= f.attachment_field :f_image1 %>
  			 <%= f.label "画像②" %><br />
  			 <%= f.attachment_field :f_image2 %></div>
  	</div>

  	<br>
	<div><%= f.submit "登録する", class:"btn btn-warning" %></div>
<% end %>
<br>
<br>

app/views/companies/member_list.html.erb
<div>
<h2><strong><%= "#{@company.name}のメンバー" %></strong></h2>
	<% if @users.blank? == false %>

		<div class="company-member-flex row col-sm-12">		
			<% @users.each do |user| %>
				<div class="col-sm-2">
					<% if Profile.where(user_id: user).blank? %>
						<%= attachment_image_tag user, :image, :fill, 100, 100, fallback: "no_image_human.jpeg", size:'100x100', class:"img-circle" %> <br />
						<p><%= user.nic_name %></p>
					<% else %>
						<%= link_to profile_path(user.profile) do %>
							<%= attachment_image_tag user, :image, :fill, 100, 100, fallback: "no_image_human.jpeg", size:'100x100', class:"img-circle" %> <br />
							<p><%= user.nic_name %></p>
						<% end %>
					<% end %>
				</div>
			<% end %>
		</div>
	<% else %>
	<p>現在メンバー登録はありません</p>
	<% end %>
</div>

<br><br>

app/views/companies/new.html.erb
<%= render "layouts/error", obj: @company %>


<h2>会社情報登録</h2>

<%= form_with model: Company.new, method: :post do |f| %>

  <div class="field">
    <%= f.label "会社名" %>
    <span class = "mandatory">&nbsp;<必須></span><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
    <span class = explanation>&nbsp; &nbsp;略称なし  入力例:'(株)'→'株式会社'と入力</span>
  </div>

  <div class="field">
    <%= f.label "フリガナ" %>
    <span class = "mandatory">&nbsp;<必須></span><br />
    <%= f.text_field :name_kana, autofocus: true, autocomplete: "name_kana" %>
    <span class = explanation>&nbsp; &nbsp;全角カタカナ</span>
  </div>

  <div class="field">
    <%= f.label "代表電話" %>
    <span  class = "mandatory">&nbsp;<必須></span><br />
    <%= f.text_field :phone_number, autofocus: true, autocomplete: "nic_name" %>
  </div>

  <div class="field">
    <%= f.label "創立年月" %><br />
    <%= f.text_field :establishment, autofocus: true %>
    <span class = "explanation" >&nbsp; &nbsp;' / 'なし<br>入力例:' 199006 '</span>
  </div>

  <div class="field">
    <%= f.label "url" %><br />
    <%= f.text_field :url, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label "メール" %>
    <span class = "mandatory">&nbsp;<必須></span><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label "郵便番号" %><br />
    <%= f.text_field :zip_code, autofocus: true, autocomplete: "zip_code" %>
    <span class = explanation>&nbsp; &nbsp;' - 'なし  入力例:' 1010001 '</span>
  </div>

  <div class="field">
    <%= f.label "住所（都道府県）" %>
    <span class = "mandatory">&nbsp;<必須></span><br />
    <%= f.text_field :address_prefecture, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label "住所（市区郡町村）" %><br />
    <%= f.text_field :address_city, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label "住所（町名 番地）" %><br />
    <%= f.text_field :address_line1, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label "住所（建物名 階層 号室）" %><br />
    <%= f.text_field :address_line2, autofocus: true %>
  </div>

  <div class="field">
  	<%= f.label "会社ロゴ画像" %><br />
  	<%= f.attachment_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "登録する" %>
  </div>
<% end %>

app/views/companies/show.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: key) %>
<% end %>

<br>	
<% if user_signed_in? %>
	<% if @company_member.present? %>	
		<div class="secret-btn-right">	
			<%= form_with(url: company_members_path, method: :delete) do |f| %>
					<%= f.submit "マイカンパニー登録を解除する", class: "btn btn-success btn-sm" %>
					<%= f.hidden_field :company_id, :value => @company.id %>
			<% end %>
		</div>
	<% elsif current_user.company_members.any? %>
		<div class="secret-btn-right">	
			<%= form_with(url: company_members_path, method: :post) do |f| %>
					<%= f.submit "他の会社でマイカンパニー登録しています", class: "btn btn-success btn-sm", disabled:"disabled" %>
					<%= f.hidden_field :company_id, :value => @company.id %>
			<% end %>
		</div>
	<% else %>
		<div class="secret-btn-right">
			<%= form_with(url: company_members_path, method: :post) do |f| %>
					<%= f.submit "マイカンパニー登録をする", class: "btn btn-default btn-sm" %>
					<%= f.hidden_field :company_id, :value => @company.id %>
			<% end %>
		</div>
	<% end %>
<% end %>

<!-- 会社情報トップ画（できれば画面幅いっぱいに表示させたい） -->
<br>
<div class="company-flex row" >
	<div class="col-sm-1.5">
		<%= attachment_image_tag @company, :image, :fill, 90, 90, fallback: "no_image_white.png", size:'90x90', class:"img-circle" %></td>
	</div>
	<div>
		<table>
			<tr>
				<td><h3><strong><%= @company.name %></strong></h3></td>			
				<% if @company_member.present? %>
					<td>&nbsp;&nbsp;<span class="label label-danger">マイカンパニー</td>
				<% end %>
			</tr>
			<tr>
				<td><%= @company.address_prefecture %></td>
				<td></td>
			</tr>
		</table>
	</div>

</div>
	
<!-- 会社情報トップ画（できれば画面幅いっぱいに表示させたい） -->


<!-- インフォメーション（PR）部分 -->
<br>
<% if user_signed_in? %>
	<% if current_user.belongs_to?(@company) %>
		<div><%= link_to "新規の募集をする", new_company_work_path(@company.id), class: "btn btn-warning  btn-sm", data: {"turbolinks" => false} %>	
			<%= link_to "トークルームを確認する", talk_rooms_path, class: "btn btn-warning  btn-sm" %>
		</div>
		<div class="secret-btn-right"><%= link_to "会社の紹介文を編集する", information_company_path(@company.id), class: "btn btn-warning  btn-sm", data: {"turbolinks" => false} %></div>
		<br>
	<% end %>
<% end %>
<div>
	<h3><strong>企業紹介</strong></h3>
	<div class="company-flex">
		<div class="image_left"><%= attachment_image_tag @company, :i_image1, :fill, 469, 250, class: "img-rounded" %></div>
		<div><%= attachment_image_tag @company, :i_image2, :fill, 469, 250, class: "img-rounded" %></div>
	</div>

	<br>
	<div><%= simple_format(@company.introduction) %></div>
</div>

<br>
<div>
	<h3><strong>今後の展望</strong></h3>
	<div class="company-flex">
		<div class="image_left"><%= attachment_image_tag @company, :f_image1, :fill, 469, 250, class: "img-rounded" %></div>
		<div><%= attachment_image_tag @company, :f_image2, :fill, 469, 250, class: "img-rounded" %></div>
	</div>

	<br>
	<div><%=simple_format(@company.future) %></div>
</div>

<!-- インフォメーション（PR）部分 -->
<br>
<div>
	<% if user_signed_in? %>
		<% if current_user.permissions == "管理者" || current_user.permissions == "企業担当者" && current_user.company_members.find_by(company_id: @company.id) %>
			<div>
				<%= link_to information_company_path(@company.id) do %>
					<button class="btn btn-warning btn-sm">会社紹介ページを編集する</button>
				<% end %>
			</div>
			<div>
				<%= link_to talk_rooms_path(company_id: @company.id) do %>
					<button class="btn btn-warning btn-sm">トークルームを確認する</button>
				<% end %>
			</div>
			<div>
				<%= link_to new_company_work_path(@company.id), method: :get, class: "btn btn-warning btn-sm" do %>
				  シゴトの新規登録をする
				<% end %>
			</div>
		<% end %>
	<% end %>
</div>

<div>
	<h4 class="subheading"><strong><%= "メンバー" %></strong></h4>
	<div class="right-link">
	<% if @users.blank? == false %>
		<div class="right-link">
			<%= link_to "ほかのメンバーもみる ＞＞", member_list_company_path(@company) %>
		</div>
		<div class="company-member-flex row col-sm-12">		
			<% @users.each do |user| %>
				<div class="col-sm-2">
					<% if Profile.where(user_id: user).blank? %>
						<%= attachment_image_tag user, :image, :fill, 100, 100, fallback: "no_image_human.jpeg", size:'100x100', class:"img-circle" %> <br />
						<p><%= user.nic_name %></p>
					<% else %>
						<%= link_to profile_path(user.profile) do %>
							<%= attachment_image_tag user, :image, :fill, 100, 100, fallback: "no_image_human.jpeg", size:'100x100', class:"img-circle" %> <br />
							<p><%= user.nic_name %></p>
						<% end %>
					<% end %>
				</div>
			<% end %>
		</div>
	<% else %>
	<p>現在メンバー登録はありません</p>
	<% end %>
</div>


<div class="btn-center">
	<%= link_to company_works_path(@company.id) do %>
		<button class="btn btn-success">
			この会社の募集一覧をみる
		</button>
	<% end %>
</div>

<div>
	<h4 class="subheading"><strong>会社情報</strong></h4>
	<div>
	<%= attachment_image_tag @company, :image, :fill, 60, 60, fallback: "no_image_white.png", size:'60x60', class:"img-circle" %>&nbsp;&nbsp;<%= @company.name %></div>
	<table>
		<tr><td><%= @company.establishment[0..3]+ "/" %><%= @company.establishment[4..5]+ " 創立" %></td></tr>
		<tr><td><%= @company.url %></td></tr>
		<tr>
			<td>
				<%= "〒" + @company.zip_code[0..2] %><%= "-" + @company.zip_code[3..6] %> <br />
				<%= @company.address_prefecture + @company.address_city + @company.address_line1 + @company.address_line2 %>
			</td>
		</tr>
	</table>
</div>

<br />
<div>
	<%= link_to "ほかの会社を探す", companies_path, method: :get, class:"btn btn-success btn-sm" %>
</div>

<div class="company-flex">
	<% if user_signed_in? %>		
		<% if current_user.admin? %>
			<div>
				<%= link_to edit_company_path do %>
					<button class="btn btn-primary btn-sm company-btns">会社の基本情報を変更する</button>
				<% end %>
			</div>

			<% if @company.is_active == 1 %>
				<div>
					<%= form_with model: @company, url: hide_company_path(@company), method: :put do |f| %>

							<%= f.hidden_field :is_active, value: false  %>
							<%= f.submit "停止する", class: "btn btn-primary btn-sm company-btns" %>	
					<% end %>
				</div>
			<% else %>
				<div>
					<%= form_with model: @company, url: reopen_company_path(@company), method: :put do |f| %>

							<%= f.hidden_field :is_active, value: true  %>
							<%= f.submit "再開する", class: "btn btn-primary btn-sm company-btns" %>
					<% end %>
				</div>
			<% end %>	
		<% end %>
	<% end %>
	<br><br>
	<br><br>
</div>