config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#top'
  get 'home/about', to: 'home#about'
  get 'recruitments', to: 'recruitments#index'

  resources :users, only: [:show, :edit, :update, :hide, :destroy, :index] do
    member do
      get 'hide'
      put 'approval'
      put 'not_approval'
      delete 'destroy_personal_data'
    end
  end
  resources :profiles, only: [:new, :create, :edit, :update, :index, :show]
  resources :companies, only: [:new, :create, :index, :show, :edit, :update] do
    resources :works, only: [:new, :create, :index, :show, :edit, :update] do
       member do
         put 'hide'
         put 'reopen'
       end
    end
    member do
      put 'hide'
      put 'reopen'
      get 'information'
      patch 'info_up'
      get 'member_list'
    end
  end
  resource :company_members, only: [:create, :destroy]
  resources :communicates, only: [:new, :create, :index, :show]
  resources :talk_rooms, only: [:new, :create, :index, :show, :destroy] do
    resource :talks, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/communicate.rb
class Communicate < ApplicationRecord
	belongs_to :user
	belongs_to :destination, class_name: 'User'

	validates :user_id, presence: true
	validates :destination_id, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :company_members, dependent: :destroy
	has_many :users, through: :company_members
	accepts_nested_attributes_for :company_members

	has_many :works, dependent: :destroy
	has_many :work_users, through: :works
	accepts_nested_attributes_for :works

	has_many :talk_rooms, dependent: :destroy
	has_many :talk_room_users, through: :talk_rooms
	accepts_nested_attributes_for :talk_rooms

	validates :name, presence: true
	validates :name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
	validates :establishment, length: {is: 6}
	validates :email, presence: true, length: {minimum: 5, maximum: 50}
	validates :zip_code, length: {is: 7}, format: { with: /\A[0-9]+\z/, message: 'はハイフンなし、半角数字で入力して下さい。'}
	validates :address_prefecture, presence: true, length: {minimum: 1, maximum: 5}
	validates :address_city, length: {maximum: 15}
	validates :address_line1, length: {maximum: 30}
	validates :address_line2, length: {maximum: 50}
	validates :phone_number, presence: true, length: {minimum: 3, maximum: 15}, format: { with: /\A[0-9]+\z/, message: 'はハイフンなし、半角数字で入力して下さい。'}
    validates :introduction, length: {maximum: 1000}
    validates :future, length: {maximum: 1000}

	attachment :image, destroy: false
    attachment :i_image1, destroy: false
    attachment :i_image2, destroy: false
    attachment :f_image1, destroy: false
    attachment :f_image2, destroy: false
end

app/models/company_member.rb
class CompanyMember < ApplicationRecord
	belongs_to :company
	belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	belongs_to :destination, class_name: 'User'

	validates :user_id, presence: true
	validates :destination_id, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :introduction, length: {maximum: 250}
  validates :future, length: {maximum: 250}

  enum employment_type: {both: 0, contract: 1, engaging: 2}
end

app/models/talk.rb
class Talk < ApplicationRecord
	belongs_to :talk_room
	belongs_to :user
end

app/models/talk_room.rb
class TalkRoom < ApplicationRecord
	belongs_to :company
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :profile, dependent: :delete

  has_many :company_members, dependent: :destroy
  has_many :companies, through: :company_members
  accepts_nested_attributes_for :company_members

  has_many :works, dependent: :destroy
  has_many :work_companies, through: :works
  accepts_nested_attributes_for :works

  has_many :talk_rooms, dependent: :destroy
  has_many :talk_room_companies, through: :talk_rooms
  accepts_nested_attributes_for :talk_rooms

  has_many :talks, dependent: :destroy
  has_many :talk_rooms, through: :talks
  accepts_nested_attributes_for :talks

  # メッセージ送信側
  # 送信者のUserから見て、宛先（受信者）のUserを(中間テーブルを介して)集める。ユーザーの判別は 'sent_msgs(送信者)'カラムで行う。
  has_many :communicates, foreign_key: 'user_id', dependent: :destroy
  # 中間テーブル(messages)を介して「destination」モデルのUser(宛名)「destination_id」を集めることを「sent(送信済みメッセージ)」と定義
  has_many :sent_msgs, through: :communicates, source: :destination

  # メッセージ受信側
  # 受信者から見て、送信者のUserを(中間テーブルを介して)集める。ユーザーの判別は ’destination_id(宛先)’カラムで行う。
  has_many :receive_communicates, class_name: 'Communicate', foreign_key: 'destination_id', dependent: :destroy
  # 中間テーブル(messages)を介して「user」モデルのUser(送信者)「user_id」を集めることを「received_msgs」と定義
  has_many :received_msgs, through: :receive_communicates, source: :user


  validates :name, presence: true, length: {minimum: 2, maximum: 30}
  validates :name_kana, presence: true, length: {minimum: 2, maximum: 30}, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :nic_name, presence: true, length: {minimum: 2, maximum: 10}
  validates :birthday, length: {is: 8}
  validates :email, presence: true, length: {minimum: 5, maximum: 50}
  validates :zip_code, length: {is: 7}, format: { with: /\A[0-9]+\z/, message: 'はハイフンなし、半角数字で入力して下さい。'}
  validates :address_prefecture_name, length: {minimum: 1, maximum: 5}
  validates :address_city, length: {maximum: 15}
  validates :address_line1, length: {maximum: 20}
  validates :address_line2, length: {maximum: 20}
  validates :phone_number, length: {minimum: 3, maximum: 15}, format: { with: /\A[0-9]+\z/, message: 'はハイフンなし、半角数字で入力して下さい。'}

  enum sex: {男性: 0, 女性: 1}
  enum permissions: {nomal: 0, company_rep: 1, admin: 2}

  attachment :image, destroy: false


  def belongs_to?(company)
    self.company_rep? && company.users.include?(self)
  end
end

app/models/work.rb
class Work < ApplicationRecord
	belongs_to :company

	validates :introduction, presence: true, length: {maximum: 500}
	validates :job_details, presence: true, length: {maximum: 2000}

	attachment :image, destroy: false	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def top
		@works = Work.all.order(created_at: :desc).limit 6

	end

	def about
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/talk_rooms_helper.rb
module TalkRoomsHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/informations/new.html.erb
information # new page

<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: key) %>
<% end %>

<h2>会社紹介登録</h2>

<%= form_with model: @informaiton, url: company_informations_path, method: :post do |f| %>

	<h3>会社紹介文</h3>
		<div><%= f.text_area :introduction %></div>
		<div><%= f.label "画像①" %><br />
  			 <%= f.attachment_field :i_image1 %>
  			 <%= f.label "画像②" %><br />
  			 <%= f.attachment_field :i_image2 %></div>

	<h3>今後の展望</h3>
		<div><%= f.text_area :future %></div>
		<div><%= f.label "画像①" %><br />
  			 <%= f.attachment_field :f_image1 %>
  			 <%= f.label "画像②" %><br />
  			 <%= f.attachment_field :f_image2 %></div>

	<div><%= f.submit "登録する", class:"btn btn-warning" %></div>
<% end %>

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>

      <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkersPark</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header class="container-fluid">
          <div id="slidemenu">
              <% if user_signed_in? %>
                <%= link_to user_path(current_user.id) do %>
                  <%= image_tag('logo_clear.png', width: '224', height: '49') %>
                <% end %>
              <% else %>
                <%= link_to root_path do %>
                  <%= image_tag('logo_clear.png', width: '224', height: '49') %>
                <% end %>
              <% end %>

            <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
              <li><%= link_to "カイシャ一覧をみる", companies_path %></li>
              <li><%= link_to "シゴト一覧をみる", recruitments_path %></li>
              <li><%= link_to "プロフィール一覧をみる", profiles_path %></li>
              <% if user_signed_in? %>
              <li>
                <% if current_user.profile.blank? %>
                  <%= link_to "プロフィールを登録する", new_profile_path(current_user.id) %>
                <% else %>
                  <%= link_to "自分のプロフィールを見る", profile_path(current_user.profile.id) %>
                <% end %>
              </li>
              <li class="">
                <%= link_to user_path(current_user.id) do %>
                  <%= attachment_image_tag current_user, :image, :fill, 50, 50, fallback: "no_image_human.jpg", size:'50x50', class:"img-circle" %>
                <% end %>
                </li>
                <li class="">
                  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
                </li>                        
              <% else %>
                <li class=""><%= link_to "Ａｂｏｕｔ", home_about_path %></li>
                <li class="">
                  <%= link_to "ログイン", new_user_session_path %>
                </li>
                <li class="">
                  <%= link_to "新規登録する", new_user_registration_path %>
                </li>
              <% end %>
            </ul>
          </div>    
      </header>
      
    <div id="wrapper">
      <main id="main-wrapper" class="container">
        <%= yield %>
      </main>
      <footer class="fixed-bottom">
          <br>
          <p>Workers' park</p>
          <br><br><br>
      </footer>
    </div>
  </body>
</html>